Exposure functions, Survival and Resistance
rafaqz/Dispersal.jl pull request #86
Opened 2021-02-02 16:21 UTC by virgile-baudrot

# Description

[Describe what this PR adds to the package]

## Changes (choose one only, with x or click after creating PR):

- [ ] New formulation/rule
- [ ] Documentation
- [ ] Bug fix for existing rules (non-breaking syntax)
- [ ] Major change to existing rules (breaking syntax, needs a breaking version bump)

# Checklist:

- [ ] My code follows the [BlueStyle](https://github.com/invenia/BlueStyle) style guide
- [ ] My code is commented with explanations of anything hard to understand
- [ ] There are no unnecessary or unrelated code changes included in this PR
- [ ] There are no depencecies added: if so, please consider if they are necessary and explain why they are required

### For bugfixes

- [ ] My PR addresses a single bug/connected group of bugs
- [ ] I have included a test that will ensure the bug does not recur

### For new `Rule`s

- [ ] My PR is limited to a clear theme/cenceptual unit. (Otherwise make multiple PRs that can be discussed separately)
- [ ] New rules have tests in a file of the same name as the rule file, e.g. `/test/newrulename.jl`
- [ ] I have cited the source of the new formulation/s, if applicable
- [ ] I have added a documentation string to formulation struct/s, and added an entry in the docs

2021-02-02 16:23 UTC, virgile-baudrot commented
It's just a Draft pull request, I've to check all the PR points are ok to be ready for review

2021-02-02 19:05 UTC, virgile-baudrot commented
well, I'm going to revise my PR...

2021-02-03 23:43 UTC, rafaqz requested changes
Ok reviewed this, code and tests look nice, but not BlueStyle and its very long!

Can you do exposure.jl, survival.jl, and resistance.jl separately in new PRs? incorporating these comments and applying BlueStyle to everything. 

I'm mostly repeating myself throughout and there are too many things to take in and discuss. I think I misunderstood this and you were going to change that anyway, but hopefully this is helpful too :))

Really we should be just talking about the formulation and whether the tests are good enough.

2021-02-03 23:43 UTC, rafaqz commented on src/Dispersal.jl
> +export Threshold_Exposure, Rotation_Exposure
No underscores in type names - so `RotationExposure`

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +    popThreshold=POPULATION_THRESHOLD,
snake case for fields: `pop_threshold`, or better `popthreshold`

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +Exposure by several treatments in rotation depending on a threshold layer (population size) set with `popThreshold`.
Add a signature for the constructor so people can see how to build this struct

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +"""
Add a signature for the constructor in the doc string, something like:

```julia
Threshold_Exposure{R,W}(;
    crop,  pulseLevel,  popThreshold,  degradationRate,  timestep,
)
```
See the other files for examples.

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +    "key layer for occurence of plot"
Can remove these doc strings and instead write them in the main doc string under an `## Arguments` header.

```julia
- `popthreshold`: some description
```

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +Base.:*(x::Number, rs::RotationStruct) = RotationStruct(x * rs.rotationStep, rs.timeStep)
Will also need one method for division by a scalar.

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +Base.:-(rs::RotationStruct, x::Number) = RotationStruct(rs.rotationStep - x, rs.timeStep)
Probably don't need to add or subtract scalars?

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +isEqualStep(rs::RotationStruct, y::Number) = rs.timeStep == y ? true : false
`isequalstep` or `isequal_step` or something if you really need an underscore. No capitals in function names

2021-02-03 23:43 UTC, rafaqz commented on src/resistance.jl
> +Lande Equation application
Constructor signature at the top of the docs, more explanation of the equation (citation if possible), and list of the arguments as above.

2021-02-03 23:43 UTC, rafaqz commented on src/survival.jl
> +Extends CellRule for rules of survival effect
Can remove the performance hint its not always true now! (the general performance got too good so chaining rules might slow it down by increasing the page size of the function)

2021-02-03 23:43 UTC, rafaqz commented on src/survival.jl
> +Logistic Survival.
Add the constructor signature and the list of arguments

2021-02-03 23:43 UTC, rafaqz commented on test/resistance.jl
> +    pesticide =  [0.0 0.0 0.0;
Make the columns line up

2021-02-03 23:43 UTC, rafaqz commented on test/resistance.jl
> +                0.0 1000.0 0.0;
Make the matrix columns line up, or use a single line.

2021-02-03 23:43 UTC, rafaqz commented on test/resistance.jl
> +PopPhenotype = population .* (meanPhenotype .+ pFreqinit.^2 .* deviationPhenotype + 2 .* pFreqinit .*(1 .-pFreqinit) .* dominanceDegree - (1 .-pFreqinit).^2 .* deviationPhenotype)
Line is too lone

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +    CheckReturn(i) = [output[i].pesticide1[1] , output[i].pesticide2[1], output[i].pesticide3[1]]
functions are lower case/snake case: `checkreturn(i)`. This looks like a type constructor to me.

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +    RS(x,y) = Dispersal.RotationStruct(x,y)
This uppercase method is fine, as its actually a constructor and it suggests that.

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +
Add some comments to this, its hard to understand what this is for. You can also make the testset descriptions more descriptive and make them nested, if that helps.

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +    US(x,y) = Dispersal.updateStep(x, y)
this isn't a constructor, it should be lower case (both US and updateStep)

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +
Put this in a testset with a descriptive name of what is being tested. The tests look good, but its not immediately clear what you are testing

```julia
@testset "can take modulo of RotationStruct" begin # Or something, I'm not sure what it does!
    @test mod(RS(1,2),2) == mod(1,2)
    @test mod(RS(2,2),2) == mod(2,2)
    @test mod(RS(2,3),2) == mod(2,2)
    @test mod(RS(3,2),2) == mod(3,2)
end
```

2021-02-03 23:43 UTC, rafaqz commented on test/growth.jl
> +        1.0 1.0 1.0;
line up the matrix or make it one line

2021-02-03 23:43 UTC, rafaqz commented on test/growth.jl
> +        2.0 2.0 0.5;
line up the matrix or make it one line

2021-02-03 23:43 UTC, rafaqz commented on test/resistance.jl
> +output[Ti(1)]
Should these be tests?

2021-02-03 23:43 UTC, rafaqz commented on test/resistance.jl
> +PopAlleleFreq = population .* pFreqinit # all are SS
variables are lowercase or snake_case

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +    ruleTreatment1 = Rotation_Exposure{Tuple{:pesticide1,:population,:rotation}, Tuple{:pesticide1,:rotation}}(
variables are lowercase or snake_case: `rule_treatment1`

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +        population = [100000.0 100.0 0.0; 0.0 1000.0 0.0; 0.0 0.0 100000.0])
NamedTuple syntax:
```julia
(
        pesticide=[0.0 0.0 0.0; 0.0 32.13061319425267 0.0; 0.0 0.0 32.13061319425267],
        population=[100000.0 100.0 0.0; 0.0 1000.0 0.0; 0.0 0.0 100000.0]
)
```

No spaces in `x=y`, to distinguish it from variable assignment. And the bracket outside the list, although I don't really mind either way.

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +    ruleTreatment = Threshold_Exposure{Tuple{:pesticide,:population}, :pesticide}(crop=Aux(:crop), pulseLevel=20, popThreshold = 1000)
`rule_treatment`

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +        population = [100000.0 100.0 0.0;
line up the matrices or make them one line.

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +    crop = reshape( # TODO: something that change with time
If this TODO is important, do it now ;) 

No one will do it later!

2021-02-03 23:43 UTC, rafaqz commented on test/exposure.jl
> +        pesticide2 = zeros(nr,nc),
always a space after commas

2021-02-03 23:43 UTC, rafaqz commented on src/exposure.jl
> +        @fastmath pesticide * exp(- rule.degradationRate * rule.nsteps)
no space after minus sign here

2021-02-03 23:43 UTC, rafaqz commented on src/Dispersal.jl
> +include("exposure.jl")
probably one file per PR is easier here, this is much too long

2021-02-04 08:46 UTC, virgile-baudrot commented
Fine, I close this one and reopen new oneS with your suggestions 👍

2021-02-04 08:46 UTC, closed without merging